language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
cache: bundler
deploy:
  provider: heroku
  api_key:
    secure: "cd+kfdlFeolicAlVC98vwO2HLsWOB65Whpdf9D5jw3MIEINh7xZhQVtblEKVZhVll6ruTNbRwS6YrX9bFXN4wPlaoOamfaFx4Cv+Y26n/MqsWDvFMktBrAEKyLKoXS2PsF+rokKk+n10xGpTzFhA+LEXMvdvCxEM95KqWMAEIF9DrTZMw+MfMsyg/DcAunurdl5uL/2GHn+6ATlk9sdIK3IdiX9wj1Cj1MmoF8Zo2AW4wQItQK2vxPl1CRaSfP0klUoh3dyjyHSS7AKF/4j6+UaP9eo+nhRZUbKwKy25VrRDKdTJzUfz/UML4q+TFB1Y3FrQy6xmneukcqDJdkpW0nCtSQREoT6n9TWusMs6dR/JSpRoYVYQOHBD5ecF4W8C8MuKGbpK0qcZSanWkwYEIOf2Q8488SyYKk+jFFkvyC4b1fcfWCnrzAlRLmAynft0BclY6OCPOe3kGuBSSHWtYvXkagWv+fKLiF8/clE3W5/hzmfVW9KsNH3DE3V44fNE9geHuenbwCaEpqHyfWn4ynfIorhOuoWAwLbByL3eakGpI/kMyOSEbSOvhABji16HnEkppWq/yZkGvMBy+Mxk5pZNU1LzXGG1MRELMoepRFFWvUIbAWzix4o2L+NQLv3sACxfXVpLsF063B/3NCruVk+i4NAeFIwHrQcsZJeiZPM="
  run: rails db:migrate
  on:
    repo: cpfergus1/viewing_party
    branch: main
  skip_cleanup: "true"
