language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
cache: bundler
deploy:
  provider: heroku
  api_key:
    secure: U+eBUaeLApuKUCvj41zjn4PUJFbCRoK2R2EJxMB88i5FCXxqa+nCieNV1pwqxuZ3nmM4zldyDaK1I4YGX7+LkeCadTHdCZGWX3X9pJrSFlEnDnjTBkTLdWzmC/8B4+ZFc8hrOMpQx5QriHJxciWagD8TIP43sBcbFn+ODFJyRb97+7Bq42kWuiZqWKG/2h/xQea6oUmArM768zokR4yyS0VL3RRdOj11iUVFzTPz3gBvaOC2GpvpRO9N3K8XPeEjgd2rib1G2TEpszSdPDUa2WtCqxrgfIkzGCk0wczy3tY1iLH8hGkLSAKUuBEWae5fQC+/WQDT4a96yi4U/i446+ukiDlBZlOVyO9F+MEYUNuK1irnvup/8NdC3370HSbe55n4x4LKFwkZaxZ38ZlytVt537XcZKLuwjGFAHj8tslfEqWWr+vUvThbDamXux49oD1xSQrfIg+7Ouy/99A2gxQMrGioeifntW8/2GtIo3kYFU/ETbSC8BBF1LXC85rRiwa0e345NxIxZAQrzwPNxCTMLHewHb6rgTaA5ITznI0UWPu9yo8qyxA4Sod+VU7+UqlA6xJRvmho+V5FikRBfumxfQ5V5Pq3TISWmvtUkdjVhAhTZW4vOQ9pRyuk7Txo+DgzeVPMuPPLxl32cN3OexutNXU2BktLz9+k4fnQxGg=
  app: agile-retreat-25350
  run: rails db:migrate
  on:
    repo: cpfergus1/viewing_party
    branch: main
  skip_cleanup: 'true'
