language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
cache: bundler
deploy:
  provider: heroku
  api_key:
    secure: EJFkW/VKRLf+UT9tXEZzY29Aq6VfmVyjduDED9cuygZhwfluhiFLjzZF6ZmnUIMzhXYMy1ghdlmyR9CPfOqUM3xWcFbBrZRXKL7R+OzK+bmezFWF1UP000JcwRuJfDf+2WMpcS8Qta9/xUl0u9lYSZyYiMPlAi9P6XPMKnVjsxCqgWVnd6Q6NYFmZ6hBpJVbVLf8noqFgNtBwWA6lqDWMMRqCcjupouOsKIeLz2tPNgWpgz2rngAnNlOxYsJSYWy1HlOsQYTjgJ43YYHYt1ecpSmvumJ9rkxtPimWdutCPbRxnxcnoTZN01ezKGzqq7D4Nn7Zc4w29R03xFVvs097ZGeUgv4U14eyEZYP9LmhPCi+PpCpl/Q1U0GBNbdgLMPDKtPNfgO2sOa4GPQa63LueODGhwR4p7JAn62lU1nCqdDzPI16BnKwv2R4HeuxWpa1f8FDG+bXr+AKPPAvxAuI3PQLYpdQwHYqOeegnPWdMu7vVMKujlKK4zH/Q2rKa4kD6K45Rmn+r4Qi5uVqO/gGpny0wcXVqR3K00lEeShPV94SkW8pm9k2qTZK9IVyLutfEP+DMsSVYntq/K7HuL/BImY/kPBVBQC3RoKVXR+w/bcNTECXBYFR6c4bxL/qrhIU463zWA0EPFh2xlui6kmpVGysnHPWlWHs1ViDD7KBaA=
  run: rails db:migrate
  on:
    repo: cpfergus1/viewing_party
    branch: main
  skip_cleanup: 'true'
