language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
cache: bundler
deploy:
  provider: heroku
  api_key:
    secure: ky1gbz9O6GJ42DST/i5SwSQMlB0hMXFCEU8Yvh211I7RgkiqauQpx6pyidTKvP4q8E1yKnSM1lqBa40wqqVss4a8rzVCyQicVBP9k0xhcyxSAmck9h+R/1eUbaXMG2JKNzddC8p+sNKZ/TZqjfBbhgjd01692pKE5MKN/aBGBdP+5w/k1FErpUN8GYIRP0LuNQDHLGPIY1+6btb7QdEFsIO9A6mNv8C+Ta74l91zbZVnP1Tp0VCVsQpxtVfntCAdngaoLbhBhFXC20YjLXW3Q6Qj6OzqgEbrRzb+pm6cmC5odU1Z29U27rAfcIR4cuqU3khrfGUqR8ndSn3f7c+mmH4RmtXiB/0PpXj+nKxy04ELRrmOX4nhsZ3qjWmTVKB/4f+JAxLKtms27MeJDOdgDMk3PKgBwEOzeRyz10IZ98TOYEBm4HLd3klqRh5w1qCXRSQlVCSBiVlXiQju9lDI6oG+NsS1iV8vmwrtSezhA5ORHkf+ef7tKx2U8CX4lIABdoSZ/u2ermYRHMQacuegmlHQOINRrDR4vNon+hm9yfioIrd/6v4/0Mft27HQhSvQl3KVIDOT/lBgt6vicoR/I950MRtdxtktplWoHqho6xt5ap/WHsn7VHysqVtcQ6GfkjSboP87fdnxku8QNy1rLhstIPzTcjbt0B6/G+JYlPE=
  app: agile-springs-75621
  run: rails db:migrate
  on:
    repo: cbartell/viewing_party
    branch: main
  skip_cleanup: 'true'
env:
  global:
    secure: "EN1ofsuD17xbcysvypdN3MtKU/CZwkJUWuS40Qal4pOj/MXXzUVPOSd7bcSLb54GYJUd7eF99AdQzWaxLllPYwshd/6ZE8ufvZTOZM04RWmhPyqwzBwNZtp4OcN6/sdzHF8FSRjyx6/zJIfkql0LuKcSpU6Qd0fV7o6CPraFoiKankDBeMeF4Cev9MRXUOEpdtm+DLdAZG5gVPZzLNiEtPg4Pqn7d2H0Hb4bDGWWM5xbdqNAx7+ThZ81Prsi/QaK/QGSkL00oYamSlaZGWhYtmf+fYpoZsA641xke34qTzPP1rGEv/555zIlUVVYCHryDYIVeCmO2HiFPJE7WWk0zpfXWbjOextu57Ru2QRsRRC20T3UALUNXhLDf4y+A6N354RrcTdYZjLEFh+9lHFdVnjzjPC0Yrq9pma8BfCULAEJEztvSHgLB4HszdwxNlWSki2XXmnE9CBb3ULTYky4LKNjMXrj2dRtIzbpvw82DOMRuoN8KHQqTolhUgXbJ+RQZ90swMSkFf1C1EiJ9jVAtUnVLaaKoob7nFUQdk1S+9OQK47jn8XGxLyZK7J6DOs1b/4EfDbglXUafYbBaXmlUbi+uNefnMQbevb4J4WiRuwFT+XTkNoJOMF/kGP1pBi+98H1obgkSNeWLNsRLU0bmnMzdQZBpTTZW2La+bjnHMQ="
