language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
cache: bundler
deploy:
  provider: heroku
  api_key:
    secure: bjDEpPVB0NqNtIlNaPoWIzRMU4r8/twLTIsHb05MHtGUZv6x07lkNXAsnr9Lh06/O04r0zRv8OZdssPkecvacJETNncn0dhQKhGbuvpavbvSyfaeTlMuPhvwt1Y4lFsHq4YSx0e6SILVKqyYLoY/TuIkX4CwU/p18Jrx5NS8tnAuKjoeb3gadYZTafpckf63Ll6PFjCXDfc2eYkCUPgHCMsyPaZe6356RlnoLT+8FKyTuoEtr03IscKpQG9zf+m22kM7JjZdYmKjRFaNKFRabY/2UWxn+YVKp5X8UOeacerG/TZT4jHJy62vqwhuPG6KyR3DKMbl9XW+X2Hz/qfoGe/c43gWPteJ3mFGsKC07CPq8LZBKXkCjIKg1Dd1j+BrESUw2OREEnAyyvwiM2Br2jPmeeshHsbe9wxfhxdWm1BTd6paKZa0NDE/3RBm5nnBxj18L990S7h5nK1uJnEjR2eksSA4eUlaYthT03fgfvC1vDVrRzatBswkv8nOGAwUHz0CPT1aXAfwmX0a6gh8h6PUSXs2qbwLGNC+E39zAAP2O0GDi3zoUPjGcti4feswE4c/d7KJq5lEKf2+umgBuXWIkcFLYabWPfeMF00kh41IY878rqcY8SrbMb8EW9aWUXfyuULiXaB+a1KZMhwNogaTw/uFPmmcjQmes0zb0a8=
  app: agile-retreat-25350
  run: rails db:migrate
  on:
    repo: cpfergus1/viewing_party
    branch: main
  skip_cleanup: 'true'
