language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
cache: bundler
deploy:
  provider: heroku
  api_key:
    secure: Z1oPuuQmhjxUJwLEuixN9+Nhu/WQsUaZFAEWiqRpGx4Bt97/XfkoStNvijfDd5Qcpw/hogmwYto98AK7DR/1P3BTPAYXxR+PEEQiJjVmMvR/LsLtV1DL2Ff3kP5CGCFJnWry5uSCQqf7p4rWx/wg85znLbCBiiJXM0JHiDIFRIK6lc+B5KnFtj4bR8LWlU1WUhSp9hitc38Gj8miCBIUE7/85kyM0DjQlknxq1pzU/jp/xRdiwXdBPSGVRT/rFEkMFOuRjK41JtRTsvph3UkMKGg/Aq6fOcmZMvd9YDWOGt6IeYjstCJNNvHD9iu5Vn5WuZdD9PtcUZ/Yu2CexTVjTdhJkVmwxmwyQgQwa/7xYEIJlPKP7Skwb3frXYvk22artUty5V1oYCHvXiEcat8mQxDzj0QQ1EVwzH2o/rOJD25fwoEfR5hGvjdaUtMbjpCfHVppgzGYm0zug9w3axUAX0Q/jUQJR4w8iXibxhNz+Zeq4xJkSQZRb9hGMqQMs8BWhI8aczicazLnNTW3UpZwFmTtvK6jZ48AFNMynhRTCm+LyNDI2Ry7gK2SEvY7JkCa7eWxI9iytS4LV2COBIwtq6zROMb0zGd7mSpwCLtIbEBHKeeSxd0WlFC3faqN9g4b/ZBz/94ZSXQhEGUn6/8f/Z4gqRRZj9aA0bNoy5Q1Oo=
  app: agile-retreat-25350
  run: rails db:migrate
  on:
    repo: cpfergus1/viewing_party
    branch: main
  skip_cleanup: 'true'
env:
  global:
    secure: j19+zqI/ab63LVQpZEsSzCtqErqUXnzg7SB6oD6T87eW/KBfLbwx9abeKzvlYSNe0esujNJqnahdSesp92LuIGRDsDU/U3cp7Z06zOt/qpLdOsr8BTtNTBFsYhFJ+hOaHaXaY931Rk88346qE8mtcCPlzCl0bOotyvBX1wuSY7vTR2oBpfZ+zUgJIMNS/PgvPK9fQwrShxhfHAK+6oy/ygd4z4ADJ4B31JAExYFLZmYuHNNmkX8l9tchbRqsdUgtuhKhfdrP/1PZXw/3/U23G5fcAajYoCyuSifafzEx1J9xrTKtGfnUlI6NqHQEqClS1IYAPQnNAenLqJdEljZhlWI0GXkiR3a4+tt9oDNB2DmfSycbqZv/m9JG0J42daVdrlxxkR4wIQAUIsRTBdfVSNbRFC2pMzrvnuUGr0kDupChNmO+dbOHqNllmxwdrObqGouT3OV0mC/Kkw/hQ/1YQQc5Xgbb1m3Sor3U+KNpS5l1ObaZ+CYFpuEpWyW/HjR5YD4YMwkw6jBxwuT9JQJi+mRDSDbHk5r+0T+s6+SCQjWM/T+tICBbURI1A6nOLdf2iC1FV35BJWs2cqa98qA8DU98Qlx/B6+FSmbADvr9BAmP2Fbw4WPaEIB6PvhQ/43jQWRjgcqvrr1Htu4vNgRWfCXMZk2j+kPmvwSbB9+HPXU=
